// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Admin.Models
{
    public partial class SeatingPlans
    {
        [Key]
        public Guid Id { get; set; }
        public Guid ReleasedDateTimeId { get; set; }
        public Guid MovieId { get; set; }
        public Guid RoomId { get; set; }
        [Required]
        public string PositionStr { get; set; }
        public string BookedStr { get; set; }
        public DateTimeOffset CreatedDateTime { get; set; }
        public DateTimeOffset? UpdatedDateTime { get; set; }
    }
}