// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FrontEnd.Models
{
    public partial class Invoices
    {
        [Key]
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public Guid MovieId { get; set; }
        [Required]
        [StringLength(10)]
        public string BookedSeatStr { get; set; }
        public Guid RoomId { get; set; }
        [Column(TypeName = "money")]
        public decimal TotalAmount { get; set; }
        public DateTimeOffset CreatedDateTime { get; set; }
    }
}