// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FrontEnd.Models
{
    public partial class Rooms
    {
        [Key]
        public Guid Id { get; set; }
        public int RoomNo { get; set; }
        [Required]
        public string SeatPositionStr { get; set; }
        public string SeatPositionJson { get; set; }
    }
}